# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - codedev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://codedev.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_09408e1bc2184fd8a4ff9c72f9bfc6cc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3f8dbe376dff4148b53f7b8ddb09aa57 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: codedev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_09408e1bc2184fd8a4ff9c72f9bfc6cc }}/codedev/codedev/react-docker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'codedev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1cc8c34033a24a6fb3c2f0b26dea87de }}
        images: 'codedev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_09408e1bc2184fd8a4ff9c72f9bfc6cc }}/codedev/codedev/react-docker:${{ github.sha }}'